sudo: required
dist: trusty
language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - autoconf
      - automake
      - make
      - xutils-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libstartup-notification0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-util0-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxcb-randr0-dev
      - libxcb1-dev

before_install:
  - sudo add-apt-repository -y 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
  - sudo apt-get update -qq


install:
  - sudo apt-get install -y --force-yes flex/trusty-backports libfl-dev/trusty-backports

  - git clone --recursive https://github.com/DaveDavenport/rofi
  - cd rofi
  - autoreconf -i
  - ./configure
  - make
  - make install

script:
  - autoreconf -i
  - make
  - ./configure
  - make
