language: c
compiler:
  - clang
  - gcc

install:
  - git clone --recursive https://github.com/DaveDavenport/rofi
  - cd rofi
  - autoreconf -i
  - ./configure
  - make
  - make install

script:
  - autoreconf -i
  - make
  - ./configure
  - make
